"""
DailyHands - Demo Data Cleanup Script
======================================
Safely removes demo data generated by seed_demo_data.py

SAFETY:
- Only removes data marked with [DEMO]
- Does NOT touch real user data
- Provides confirmation before deletion
- Shows what will be deleted
"""

import sqlite3

DATABASE = 'dailyhands.db'
DEMO_MARKER = '[DEMO]'

class DemoDataCleaner:
    def __init__(self):
        self.conn = sqlite3.connect(DATABASE)
        self.conn.row_factory = sqlite3.Row
        self.cursor = self.conn.cursor()
        self.to_delete = {
            'ratings': [],
            'agency_earnings': [],
            'payments': [],
            'attendance': [],
            'request_workers': [],
            'request_worker_types': [],
            'work_requests': [],
            'workers': []
        }
    
    def find_demo_data(self):
        """Identify all demo data to be deleted"""
        print("=" * 70)
        print("Scanning for Demo Data")
        print("=" * 70)
        
        # Find demo workers
        self.cursor.execute(
            "SELECT id, name, skill FROM workers WHERE name LIKE ?",
            (f"%{DEMO_MARKER}%",)
        )
        demo_workers = self.cursor.fetchall()
        worker_ids = [w['id'] for w in demo_workers]
        
        print(f"\n✓ Found {len(demo_workers)} demo workers")
        for worker in demo_workers:
            print(f"  - {worker['name']} ({worker['skill']})")
            self.to_delete['workers'].append(worker['id'])
        
        # Find demo work requests
        self.cursor.execute(
            "SELECT id, title, status FROM work_requests WHERE title LIKE ?",
            (f"%{DEMO_MARKER}%",)
        )
        demo_requests = self.cursor.fetchall()
        request_ids = [r['id'] for r in demo_requests]
        
        print(f"\n✓ Found {len(demo_requests)} demo work requests")
        for request in demo_requests:
            print(f"  - {request['title'][:60]}... ({request['status']})")
            self.to_delete['work_requests'].append(request['id'])
        
        if not worker_ids and not request_ids:
            print("\n✓ No demo data found. Database is clean.")
            return False
        
        # Find related data
        if request_ids:
            request_ids_str = ','.join('?' * len(request_ids))
            
            # Ratings
            self.cursor.execute(
                f"SELECT id FROM ratings WHERE request_id IN ({request_ids_str})",
                request_ids
            )
            self.to_delete['ratings'] = [r['id'] for r in self.cursor.fetchall()]
            
            # Agency earnings
            self.cursor.execute(
                f"SELECT id FROM agency_earnings WHERE request_id IN ({request_ids_str})",
                request_ids
            )
            self.to_delete['agency_earnings'] = [r['id'] for r in self.cursor.fetchall()]
            
            # Payments
            self.cursor.execute(
                f"SELECT id FROM payments WHERE request_id IN ({request_ids_str})",
                request_ids
            )
            self.to_delete['payments'] = [r['id'] for r in self.cursor.fetchall()]
            
            # Attendance
            self.cursor.execute(
                f"SELECT id FROM attendance WHERE request_id IN ({request_ids_str})",
                request_ids
            )
            self.to_delete['attendance'] = [r['id'] for r in self.cursor.fetchall()]
            
            # Request workers
            self.cursor.execute(
                f"SELECT id FROM request_workers WHERE request_id IN ({request_ids_str})",
                request_ids
            )
            self.to_delete['request_workers'] = [r['id'] for r in self.cursor.fetchall()]
            
            # Request worker types
            self.cursor.execute(
                f"SELECT id FROM request_worker_types WHERE request_id IN ({request_ids_str})",
                request_ids
            )
            self.to_delete['request_worker_types'] = [r['id'] for r in self.cursor.fetchall()]
        
        print(f"\n✓ Found {len(self.to_delete['ratings'])} ratings")
        print(f"✓ Found {len(self.to_delete['agency_earnings'])} agency earnings records")
        print(f"✓ Found {len(self.to_delete['payments'])} payment records")
        print(f"✓ Found {len(self.to_delete['attendance'])} attendance records")
        print(f"✓ Found {len(self.to_delete['request_workers'])} worker assignments")
        print(f"✓ Found {len(self.to_delete['request_worker_types'])} worker type requirements")
        
        total = sum(len(v) for v in self.to_delete.values())
        print(f"\n✓ TOTAL RECORDS TO DELETE: {total}")
        
        return True
    
    def delete_demo_data(self):
        """Delete all identified demo data"""
        print("\n" + "=" * 70)
        print("Deleting Demo Data")
        print("=" * 70)
        
        # Delete in correct order (respecting foreign keys)
        tables = [
            ('ratings', 'ratings'),
            ('agency_earnings', 'agency_earnings'),
            ('payments', 'payments'),
            ('attendance', 'attendance'),
            ('request_workers', 'request_workers'),
            ('request_worker_types', 'request_worker_types'),
            ('work_requests', 'work_requests'),
            ('workers', 'workers')
        ]
        
        for key, table_name in tables:
            ids = self.to_delete[key]
            if ids:
                ids_str = ','.join('?' * len(ids))
                self.cursor.execute(f"DELETE FROM {table_name} WHERE id IN ({ids_str})", ids)
                print(f"✓ Deleted {len(ids)} records from {table_name}")
        
        self.conn.commit()
        
        print("\n" + "=" * 70)
        print("✅ Demo data cleanup completed successfully!")
        print("=" * 70)
    
    def run(self):
        """Execute the cleanup process"""
        try:
            has_demo_data = self.find_demo_data()
            
            if not has_demo_data:
                return
            
            print("\n" + "=" * 70)
            response = input("\nProceed with deletion? (yes/no): ").strip().lower()
            
            if response == 'yes':
                self.delete_demo_data()
            else:
                print("\n❌ Operation cancelled by user.")
        
        except Exception as e:
            print(f"\n❌ ERROR: {e}")
            print("Rolling back changes...")
            self.conn.rollback()
            raise
        
        finally:
            self.conn.close()


if __name__ == '__main__':
    print("\n" + "=" * 70)
    print("DailyHands - Demo Data Cleanup Script")
    print("=" * 70)
    print("\nThis script will DELETE all demo data marked with [DEMO]")
    print("Real user data will NOT be affected.")
    print("\n" + "=" * 70)
    
    cleaner = DemoDataCleaner()
    cleaner.run()
